env:
    rcloneconfig: "ENCRYPTED[8051df642acc633b040a4631589408aa4338bb68da675bcdd77d7bf2ab7b6d7ccd3be22a755009b992d3b2fd26a93a8d]"
    anu: "ENCRYPTED[71fb92648bee5cedde922ec534cc8d1ddb8b828ed378ad06ff63b0857fe151213de3bb35b497f7b1164e7457acd27eb5]"
    lunch: lunch aosp_a3y17lte-userdebug
    make: mka aex
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
 
  Build-Env-Setup_background_script:
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "imannig"
       - git config --global user.email "akugedekntl@gmail.com"
       - echo "$anu" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy cirrus:aex-q/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start Sync Source"
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/rom
      - cd ~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/AospExtended/manifest.git -b 10.x -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/imannig/local_manifest -b aex .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8
      - rm -rf hardware/lineage/livedisplay    
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - echo "Lest start this fuck"
   #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
   #   - ./collect.sh
      - ./final.sh
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd ~/rom/out/target/product/juice/ && ls Nusantara*.zip) To Your Drive"
      - rclone copy ~/rom/out/target/product/a3y17lte/AospExtended*.zip cirrus:exynos7870 -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz cirrus:aex-q -P
      - echo " "
     # - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploadinig Ccahchhe Successyffully!"
