env:
    rcloneconfig: "ENCRYPTED[8051df642acc633b040a4631589408aa4338bb68da675bcdd77d7bf2ab7b6d7ccd3be22a755009b992d3b2fd26a93a8d]"
    anu: "ENCRYPTED[f9aa3070d1fafb13e576840465991c2b79b3089777fd43a9872db6a05c9e2ca77f37432a4e1bd9bfdb6ca735ed973333]"
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: 20020214/lynzx:latest
      cpu: 8
      memory: 32G
 
  Build-Env-Setup_background_script:
    #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 tmate -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "imannig"
       - git config --global user.email "akugedekntl@gmail.com"
       - mkdir -p /tmp/ccache
       - export CCACHE_DIR=/tmp/ccache
       - export CCACHE_EXEC=$(which ccache)
       - ccache --clear
       - rclone copy cirrus:nad-jus-q/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
 
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Tmate:
      - tmate -S /tmp/tmate.sock new-session -d
      - tmate -S /tmp/tmate.sock wait tmate-ready
      - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
  
  Sync_script:
   #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start Sync Source"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/NusantaraProject-ROM/android_manifest.git -b 10 -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone --depth=1 https://$anu@github.com/frostg-012/device-xiaomi-juice.git -b 10.staging device/xiaomi/juice
      - git clone --depth=1 https://$anu@github.com/frostg-012/vendor-xiaomi-juice.git vendor/xiaomi/juice
      - rm -rf device/xiaomi/juice/sepolicy/private/hal_power_default.te
  #    - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
   #   - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) To Your Drive"
#      - rclone copy /tmp/rom/out/target/product/juice/Nusantara*.zip cirrus:juice -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
    #  - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz cirrus:nad-jus-q -P
      - echo " "
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Ccache Successfully!"
